---
REPO: kodi
STAGE: false
IMAGE_VERSION: 17.6

ARCH:
- name: armv6l
  images:
    base: balenalib/raspberry-pi-debian:stretch-20200428
  tag: armv6l
  arch: arm
  variant: v6l
  platform: linux/arm/v6
  is_arm: true
  enable: false
  # enable: true

- name: armv7l
  images:
    base: balenalib/raspberry-pi-debian:stretch-20200428
  tag: armv7l
  arch: arm
  variant: v7l
  platform: linux/arm/v7
  is_arm: true
  enable: false
  # enable: true

- name: amd64
  images:
    base: debian:buster-20200514
  tag: amd64
  arch: amd64
  platform: linux/amd64
  is_amd: true
  # enable: false
  enable: true
