---
REPO: picam
STAGE: false
IMAGE_VERSION: 1.4.8
PICAM_VERSION: 1.4.8

IMAGES:
  BASE: balenalib/raspberry-pi-debian:stretch-20200405
  BUILD_BASE: balenalib/raspberry-pi-debian:stretch-20200405

ARCH:
- name: armv6
  tag: armv6
  arch: arm
  variant: v6
  platform: linux/arm/v6
  enable: true

- name: armv6l
  tag: armv6l
  arch: arm
  variant: v6l
  platform: linux/arm/v6
  enable: true

- name: armv7
  tag: armv7
  arch: arm
  variant: v7
  platform: linux/arm/v7
  enable: true

- name: armv7l
  tag: armv7l
  arch: arm
  variant: v7l
  platform: linux/arm/v7
  enable: true
